name: main

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test test -- ${{ secrets.MONGODB_PASSWORD }}
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build Container Image
      run: docker build -t registry.digitalocean.com/test-registries/life-butler .
    - name: Login Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/test-registries/life-butler
    - name: ssh pull docker and start
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: 12345678
        script: |
          ./start.sh
