name: Rust

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: ssh pull docker and start
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 165.232.170.167
        username: root
        password: ${{ secrets.MONGODB_PASSWORD }}
        script: |
          docker pull registry.digitalocean.com/test-registries/life-butler
          docker run -p 8080:8080 -e MONGO_PASSWD="${{ secrets.MONGODB_PASSWORD }}" registry.digitalocean.com/test-registries/life-butler
