name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Run tests
      run: cargo test
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 143.198.208.44
        username: root
        password: ""
        script: whoami


