name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Run tests
      run: cargo test --verbose
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build Container Image
      run: life-butler % docker build -t registry.digitalocean.com/test-registries/life-butler .
    - name: Login Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/test-registries/life-butler
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 143.198.208.44
        username: root
        script: whoami


