name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v3
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 143.198.208.44
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: whoami
