name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: create ssh file
      run: touch id_rsa.pub
    - name: write key to it
      run: echo ${{ secrets.SSH_KEY }} >> id_rsa.pub
    - name: test
      run: cat /home/runner/work/life-butler/life-butler/id_ras.pub
    - name: pu
      run: doctl compute ssh 357712721 --ssh-key-path "/home/runner/work/life-butler/life-butler/id_ras.pub" --ssh-command "docker pull registry.digitalocean.com/test-registries/life-butler;docker run -p 8080:8080 -e MONGO_PASSWD="${{ secrets.MONGODB_PASSWORD }}" registry.digitalocean.com/test-registries/life-butler"
